version: '3.9'
services:
  elasticsearch:
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    image: elasticsearch:2.3.1
    networks:
      - compose-bridge
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.4.3
    ports:
      - 5601:5601

networks:
  compose-bridge:
    driver: bridge
